version: '3.8'

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: asimkumar1986/yamdb_final:latest
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.6
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/code/static
      - ./media:/code/media
    depends_on:
      - web
